<?$APPLICATION->IncludeComponent(
	"simpletemplates:form.order",
	"",
	Array(
		"AJAX_URL" => "/smt_ajax/ajax_form.php",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CUSTOM_FORM_SUBMIT" => "Отправить сообщение",
		"CUSTOM_TITLE_100" => "",
		"CUSTOM_TITLE_101" => "",
		"CUSTOM_TITLE_102" => " ",
		"CUSTOM_TITLE_103" => "",
		"CUSTOM_TITLE_209" => "",
		"CUSTOM_TITLE_212" => " ",
		"CUSTOM_TITLE_213" => " ",
		"CUSTOM_TITLE_80" => " ",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "Сообщение",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Ваше имя",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"DISPLAY_ICON" => "Y",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"EMAIL_TO" => "",
		"EVENT_MESSAGE_ID" => array(),
		"FIELDS_ORDER" => "NAME,100,101,209,212,213,DETAIL_TEXT,102,103",
		"FORMS_DISABLE_AGREEMENT" => "N",
		"FORM_SUFFIX" => "contactpageform",
		"GROUPS" => array("2"),
		"IBLOCK_ID" => "18",
		"IBLOCK_TYPE" => "smt_form",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => array("100","101","102","103","209","212","213","NAME","DETAIL_TEXT"),
		"PROPERTY_CODES_REQUIRED" => array("100","102","NAME"),
		"REDIRECT_URL" => "",
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"SHOW_FORM_BORDER" => "Y",
		"STATUS" => "ANY",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Ваше сообщение успешно отправлено",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N"
	)
);?>