<?$APPLICATION->IncludeComponent(
	"simpletemplates:form.order",
	"",
	Array(
		"AJAX_URL" => "/smt_ajax/ajax_form.php",
		"CUSTOM_FORM_SUBMIT" => "Отправить",
		"CUSTOM_TITLE_100" => "",
		"CUSTOM_TITLE_101" => "",
		"CUSTOM_TITLE_102" => " ",
		"CUSTOM_TITLE_103" => "",
		"CUSTOM_TITLE_104" => "Проект",
		"CUSTOM_TITLE_178" => "",
		"CUSTOM_TITLE_179" => "",
		"CUSTOM_TITLE_180" => "",
		"CUSTOM_TITLE_181" => "",
		"CUSTOM_TITLE_80" => " ",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "комментарий",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Ваше имя",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "комментарий",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"DISPLAY_ICON" => "Y",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"EMAIL_TO" => "",
		"EVENT_MESSAGE_ID" => array("7"),
		"FIELDS_ORDER" => "NAME,179,DETAIL_TEXT,180",
		"FORMS_DISABLE_AGREEMENT" => "N",
		"FORM_SUFFIX" => "reviewform",
		"GROUPS" => array("2"),
		"IBLOCK_ID" => "36",
		"IBLOCK_TYPE" => "smt_form",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"OBJECT_ID" => isset($arParams["OBJECT_ID"])?$arParams["OBJECT_ID"]:"",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
"PROPERTY_CODES" => array(
			0 => "NAME",
			1 => "179",
			2 => "180",
			3 => "181",
			4 => "182",
			5 => "DETAIL_TEXT",
		),
		"PROPERTY_CODES_REQUIRED" => array("NAME","179","180","181"),
		"REDIRECT_URL" => "",
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"SHOW_FORM_BORDER" => "N",
		"STATUS" => "ANY",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Ваш комментарий успешно отправлен!",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "Y"
	)
);?>
