<?$APPLICATION->IncludeComponent(
	"simpletemplates:form.order", 
	".default", 
	array(
		"AJAX_URL" => "/smt_ajax/ajax_form.php",
		"CUSTOM_FORM_SUBMIT" => "Отправить свой проект",
		"CUSTOM_TITLE_80" => " ",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Ваше имя",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"EMAIL_TO" => "",
		"EVENT_MESSAGE_ID" => array(
		),
		"FORM_SUFFIX" => "orderformmain",
		"GROUPS" => array(
			0 => "2",
		),
		"IBLOCK_ID" => "35",
		"IBLOCK_TYPE" => "smt_form",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => array(
			0 => "163",
			1 => "164",
			2 => "165",
			3 => "166",
			4 => "167",
			5 => "210",
			6 => "211",
		),
		"PROPERTY_CODES_REQUIRED" => array(
			0 => "163",
			1 => "164",
			2 => "166",
			3 => "NAME",
		),
		"REDIRECT_URL" => "",
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"SHOW_FORM_BORDER" => "N",
		"STATUS" => "ANY",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Ваша заявка успешно отправлена",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N",
		"CUSTOM_TITLE_102" => " ",
		"COMPONENT_TEMPLATE" => ".default",
		"FIELDS_ORDER" => "163,164,165,167,210,211,166",
		"DISPLAY_ICON" => "Y",
		"FORMS_DISABLE_AGREEMENT" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CUSTOM_TITLE_100" => "",
		"CUSTOM_TITLE_101" => "",
		"CUSTOM_TITLE_103" => "",
		"CUSTOM_TITLE_163" => "",
		"CUSTOM_TITLE_164" => "",
		"CUSTOM_TITLE_165" => "",
		"CUSTOM_TITLE_166" => " ",
		"CUSTOM_TITLE_167" => "Прикрепите файлы проекта",
		"CUSTOM_TITLE_168" => "",
		"CUSTOM_TITLE_169" => "",
		"CUSTOM_TITLE_210" => " ",
		"CUSTOM_TITLE_211" => " "
	),
	false
);?>